map_nav_node:
  ros__parameters:
    wms:
      url: 'http://localhost:8080/wms'
      version: '1.1.1'
      layer: 'Imagery'
      srs: 'EPSG:4326'  # don't change this setting, internal logic may often implicitly assume EPSG:4326
      request_timeout: 5
    misc:
      mock_gps_selection: 1
      export_position: 'position.json'
      export_projection: 'projection.json'
      max_pitch: 30  # Used by _should_match
      variance_estimation_length: 20
      min_match_altitude: 50
    map_update:
      initial_guess: [37.523640, -122.255122] # Values from ksql_airport.world file
      update_delay: 1  # Keep low (e.g. 1 second) if vehicle flying fast or gimbal_projection: True
      default_altitude: 130
      gimbal_projection: True
      max_pitch: 30  # Applies if gimbal_projection: True, used by _should_update_map
      max_map_radius: 1000
      map_radius_meters_default: 400
      update_map_center_threshold: 50
      update_map_radius_threshold: 50
    superglue:  # Recommended outdoor params from SuperGlue repo's README.md
      superpoint:
        nms_radius: 3
        keypoint_threshold: 0.005
        max_keypoints: 2048
      superglue:
        weights: 'outdoor'
        sinkhorn_iterations: 20
        match_threshold: 0.2