- Information:
      - GitHub repository:
            - abbr: GH
              href: https://github.com/hmakelin/gisnav
      - Developer documentation:
            - abbr: Docs
              href: https://gisnav.org
