- Bookmarks:
      - GitHub repository:
            - abbr: GH
              href: https://github.com/hmakelin/gisnav
      - User guide and developer reference:
            - abbr: Docs
              href: https://gisnav.org
