x-gpu-x11-devices: &gpu-x11-devices
  devices:
    - /dev/dri:/dev/dri  # gpu, x11
    - /dev/vc-mem:/dev/vc-mem  # gpu
    - /dev/vcio:/dev/vcio  # gpu

services:
  gisnav:
    <<: *gpu-x11-devices

  px4:
    <<: *gpu-x11-devices

  ardupilot:
    <<: *gpu-x11-devices

  qgc:
    <<: *gpu-x11-devices

  qgis:
    <<: *gpu-x11-devices

  rviz:
    <<: *gpu-x11-devices
