# This Docker Compose file is part of the GISNav project configuration.
# It defines various services, their network associations, and port mappings
# to facilitate communication and functionality within the GISNav system. The
# port mappings here expose specific services to communication from both the
# local and any number of remote hosts.

name: gisnav

services:
  mapserver:
    networks:
      - gis

  mavros:
    networks:
      - dds
    ports:
      - "${GISNAV_CMP_MAVROS_BIND_PORT:?empty or not set}:${GISNAV_CMP_MAVROS_BIND_PORT:?empty or not set}/udp"

  micro-ros-agent:
    networks:
      - dds
    ports:
      - "${UXRCE_DDS_PRT:?empty or not set}:${UXRCE_DDS_PRT:?empty or not set}/udp"

  qgc:
    networks:
      - mavlink

  # TODO: Expose serial device instead of TCP port and output NMEA directly?
  gisnav:
    networks:
      - gis
      - dds

  px4:
    networks:
      - mavlink
    ports:
      # Expose TCP port for NMEA input via TCP at port 15000
      - "15000:15000/tcp"
    environment:
      PX4_VIDEO_HOST_IP: ${PX4_VIDEO_HOST_IP:?empty or not set}
      UXRCE_DDS_PRT: ${UXRCE_DDS_PRT:?empty or not set}
      GISNAV_COMPANION_HOST: ${GISNAV_COMPANION_HOST:?empty or not set}
      GISNAV_CMP_MAVROS_BIND_PORT: ${GISNAV_CMP_MAVROS_BIND_PORT:?empty or not set}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # TODO: Define and expose necessary ports for ArduPilot.
  ardupilot:
    networks:
      - mavlink

  gscam:
    networks:
      - dds
    ports:
      # Not needed if a local device is used as video source instead of network stream
      # see gscam_params.yaml file
      - "5600:5600/udp"

  qgis:
    networks:
      - gis

  postgres:
    networks:
      - gis

  fileserver:
    networks:
      - admin

  homepage:
    networks:
      - admin
    extra_hosts:
      - "host.docker.internal:host-gateway"

  monitoring:
    networks:
      - admin

  nginx:
    networks:
      - admin
    ports:
      # Expose HTTP port
      - "80:80/tcp"
      # Expose HTTPS port
      - "443:443/tcp"
