x-no-gpu-devices-reservations: &no-gpu-devices-reservations
  deploy:
    resources:
      reservations:
        devices: {}  # negate the default NVIDIA runtime config

services:
  gisnav:
    <<: *no-gpu-devices-reservations

  px4:
    <<: *no-gpu-devices-reservations

  ardupilot:
    <<: *no-gpu-devices-reservations

  qgc:
    <<: *no-gpu-devices-reservations

  qgis:
    <<: *no-gpu-devices-reservations

  rviz:
    <<: *no-gpu-devices-reservations
