# This Docker Compose file is part of the GISNav project configuration.
# It defines a reusable configuration layer that sets up dependencies between
# the services.

name: gisnav

services:

  gisnav:
    depends_on:
      - micro-ros-agent
      - mavros
      - gscam
      - mapserver
      - postgres
      - autoheal
      - nginx

  px4:
    depends_on:
      - mavros
      - micro-ros-agent
      - qgc

  qgis:
    depends_on:
      - postgres
      - mapserver

  nginx:
    depends_on:
      - fileserver
      - homepage
      - monitoring
