gisnav:
  gis_node:
    ros__parameters:
      wms_url: 'http://host.docker.internal/cgi-bin/mapserv.cgi?map=/etc/mapserver/default.map'
      wms_layers: ['imagery']
      wms_dem_layers: ['dem']
      wms_format: 'image/jpeg'
      min_map_overlap_update_threshold: 0.85
