# The port can be overridden via launch args in default launch file
# It probably should not be statically declared here because the appropriate
# outbound port should probably be some pseudo-tty (virtual serial port) on a
# development machine --> use launch args to provide suitable port instead
ublox:
  ublox_node:
    ros__parameters:
      device: /dev/ttyACM0
      uart1/baudrate: 9600
      rate: 5
      dynamic_model: airborne1
      fix_mode: 3d
      publish/nav/pvt: true
