ros2_topics:
  sub:
    'VehicleLocalPosition_PubSubTopic': 'px4_msgs.msg.VehicleLocalPosition'
    'VehicleGlobalPosition_PubSubTopic': 'px4_msgs.msg.VehicleGlobalPosition'
    'VehicleAttitude_PubSubTopic': 'px4_msgs.msg.VehicleAttitude'
    'GimbalDeviceAttitudeStatus_PubSubTopic': 'px4_msgs.msg.GimbalDeviceAttitudeStatus'
    'GimbalDeviceSetAttitude_PubSubTopic': 'px4_msgs.msg.GimbalDeviceSetAttitude'
    'camera_info': 'sensor_msgs.msg.CameraInfo'
    'image_raw': 'sensor_msgs.msg.Image'
  pub:
    'essential_matrix': 'std_msgs.msg.Float64MultiArray'
    'homography_matrix': 'std_msgs.msg.Float64MultiArray'
    'pose': 'std_msgs.msg.Float64MultiArray'
    'fov': 'std_msgs.msg.Float64MultiArray'
wms:
  url: 'http://localhost:8080/wms'
  version: '1.1.1'
  layer: 'WorldImagery'
  srs: 'EPSG:4326'  # util.get_bbox currently only supports EPSG:4326 --> don't change this setting
superglue:  # Recommended outdoor config from SuperGlue repo's README.md
  superpoint:
    nms_radius: 3
    keypoint_threshold: 0.005
    max_keypoints: 2048
  superglue:
    weights: 'outdoor'
    sinkhorn_iterations: 20
    match_threshold: 0.2
  misc:
    affine: False  # Consider setting to True if camera is known to be nadir-facing
    gimbal_projection: True