map_nav_node:
  ros__parameters:
    wms:
      url: 'http://localhost:8080/wms'
      version: '1.1.1'
      layer: 'Imagery'
      srs: 'EPSG:4326'  # util.get_bbox currently only supports EPSG:4326 --> don't change this setting
      request_timeout: 5
    misc:
      affine_threshold: 5
      publish_frequency: 40  # Hz
      export_position: 'position.json'
      export_projection: 'projection.json'
      max_pitch: 30  # Used by _should_match
      visualize_homography: True
      covariance_estimation_length: 20
    map_update:
      initial_guess:  # Values from ksql_airport.world file
        lat: 37.523640
        lon: -122.255122
      update_delay: 1  # Keep low (e.g. 1 second) if vehicle flying fast or gimbal_projection: True
      default_altitude: 130
      gimbal_projection: True
      max_pitch: 30  # Applies if gimbal_projection: True, used by _should_update_map
      max_map_radius: 1000
      map_radius_meters_default: 400
      update_map_center_threshold: 50
      update_map_radius_threshold: 50
  superglue:  # Recommended outdoor config from SuperGlue repo's README.md
    superpoint:
      nms_radius: 3
      keypoint_threshold: 0.005
      max_keypoints: 2048
    superglue:
      weights: 'outdoor'
      sinkhorn_iterations: 20
      match_threshold: 0.2