class_name: 'gisnav.pose_estimators.superglue_pose_estimator.SuperGluePoseEstimator'
args: # Recommended outdoor config from SuperGluePoseEstimator repo's README.md
  - 15  # _min_matches
  - superpoint:
      nms_radius: 3
      keypoint_threshold: 0.005
      max_keypoints: 2048
    superglue:
      weights: 'outdoor'
      sinkhorn_iterations: 20
      match_threshold: 0.2
