class_name: 'python_px4_ros2_map_nav.matchers.superglue.SuperGlue'
args:  # Recommended outdoor config from SuperGlue repo's README.md
  - 15  # min_matches
  - superpoint:
      nms_radius: 3
      keypoint_threshold: 0.005
      max_keypoints: 2048
    superglue:
      weights: 'outdoor'
      sinkhorn_iterations: 20
      match_threshold: 0.2
