args:  # Recommended outdoor config from SuperGlue repo's README.md
  - superpoint:
      nms_radius: 3
      keypoint_threshold: 0.005
      max_keypoints: 2048
    superglue:
      weights: 'outdoor'
      sinkhorn_iterations: 20
      match_threshold: 0.2