mock_gps_node:
  ros__parameters:
    wms:
      url: 'http://localhost:8080/wms'
      version: '1.1.1'
      layers: ['Imagery']
      styles: ['']
      srs: 'EPSG:4326'
      image_format: 'image/jpeg'
      request_timeout: 10
    misc:
      mock_gps_selection: 1 # declared by MockGPSNode, not by base class
      max_pitch: 30  # 30  # Used by _should_match
      variance_estimation_length: 20
      min_match_altitude: 80
      blur_threshold: 1.5  # standard deviations
      blur_window_length: 100
    map_update:
      update_delay: 1  # Keep low (e.g. 1 second) if vehicle flying fast or gimbal_projection: True
      gimbal_projection: True
      max_pitch: 30  # Applies if gimbal_projection: True, used by _should_update_map
      max_map_radius: 1000
      update_map_area_threshold: 0.85
    pose_estimator:
      #params_file: 'config/superglue_params.yaml'  # For parsing args for matcher's static initializer method
      params_file: 'config/loftr_params.yaml'
    debug:
      export_position: 'position.json'
      export_projection: 'projection.json'