name: Build and upload gisnav service

on:
  #push:
  #  # Run when new version tag is pushed
  #  tags:
  #    - v*

  # Allows running manually from the Actions tab
  workflow_dispatch:


jobs:
  build-gisnav-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Build .deb inside container
        run: |
          docker pull ghcr.io/${{ github.repository }}:latest
          docker run --name gisnav-build ghcr.io/${{ github.repository }}:latest cd /systemd/gisnav && make dist
          docker cp $(docker ps -q -l):opt/colcon_ws/src/gisnav/systemd/gisnav/dist/ /tmp/build-output

      - name: Find .deb file and set env
        run: |
          DEB_FILE=$(ls /tmp/build-output/*.deb)
          echo "DEB_FILE=$DEB_FILE" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: gisnav-deb
          path: ${{ env.DEB_FILE }}

  upload-gisnav-service:
    needs: build-gisnav-service
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: gisnav-deb

      # Use GitHub releases as apt repository
      - name: Upload .deb package as release artifact
        run: |
          echo TODO
