name: Build and upload gisnav Docker image to GHCR

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows running manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  upload:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout GISNav
        uses: actions/checkout@v3
        with:
          path: colcon_ws/src/gisnav

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker Buildx
        run: |
          docker buildx create --use

      - name: Build GISNav multi-arch Docker images
        run: |
          cd colcon_ws/src/gisnav/docker
          docker compose -f docker-compose.yaml -f docker-compose.multi-arch.yaml build gisnav

      - name: Tag GISNav multi-arch Docker images
        run: |
          cd colcon_ws/src/gisnav/docker
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG_NAME=${GITHUB_REF#refs/tags/}
          else
            TAG_NAME=latest
          fi
          docker tag ghcr.io/hmakelin/gisnav:latest ghcr.io/hmakelin/gisnav:$TAG_NAME

      - name: Push GISNav multi-arch Docker images
        run: |
          cd colcon_ws/src/gisnav/docker
          docker push ghcr.io/hmakelin/gisnav:$TAG_NAME
