name: Push latest GISNav multi-arch Docker images to GHCR

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows running manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  upload:
    runs-on: ubuntu-20.04
    timeout-minutes: 90
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout GISNav
        uses: actions/checkout@v3
        with:
          path: colcon_ws/src/gisnav

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # The Docker Compose gisnav service configuration is assumed
      # to use this tag for the Docker images if available, i.e.:
      # ```yaml
      # services:
      #   gisnav:
      #     image: "ghcr.io/hmakelin/gisnav:${TAG:-latest}"
      # ```
      - name: Extract git tag from GITHUB_REF
        run: echo "TAG=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/')

      - name: Setup Docker Buildx
        run: |
          docker buildx create --use

      - name: Build GISNav multi-arch Docker images
        run: |
          cd colcon_ws/src/gisnav/docker
          docker compose -f docker-compose.yaml -f docker-compose.multi-arch.yaml build gisnav

      - name: Push GISNav multi-arch Docker images
        run: |
          cd colcon_ws/src/gisnav/docker
          docker compose push gisnav
