name: Run ROS 2 launch tests

on:
  workflow_run:
    workflows: [ "Build and upload gisnav Docker image to GHCR" ]
    types:
      - completed

  # Allows running manually from the Actions tab
  workflow_dispatch:

#env:
#  REGISTRY: ghcr.io
#  IMAGE_NAME: ${{ github.repository }}

jobs:
  run:
    runs-on: ubuntu-20.04
    #container: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
    container: ghcr.io/${{ github.repository }}:latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Install GISNav developer dependencies
        run: |
          cd /home/gisnav/colcon_ws/src/gisnav
          python3 -m pip install -U -r requirements-dev.txt

      - name: Run ROS 2 launch tests
        run: |
          cd /home/gisnav/colcon_ws
          source install/setup.bash
          cd src/gisnav/test/launch
          launch_test test_px4_launch.py
          launch_test test_ardupilot_launch.py
