name: Static analysis

on:
  workflow_run:
    workflows: [ "Build and upload gisnav Docker image to GHCR" ]
    types:
      - completed

  # Allows running manually from the Actions tab
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-20.04
    container: ghcr.io/${{ github.repository }}:latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Run pre-commit
        run: |
          export PATH=$(python3 -m site --user-base)/lib/gisnav:$PATH
          cd /home/gisnav/colcon_ws/src/gisnav
          pre-commit run --all-files
