name: Static analysis

on:
  workflow_run:
    workflows: [ "Build and upload gisnav Docker image to GHCR" ]
    types:
      - completed

  # Allows running manually from the Actions tab
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Run pre-commit
        run: docker run ghcr.io/${{ github.repository }}:latest make test-static
