name: Build and upload gisnav Docker image to GHCR

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows running manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  upload:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout GISNav
        uses: actions/checkout@v3
        with:
          path: /opt/colcon_ws/src/gisnav

      - name: Login to GHCR
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push gisnav image
        run: |
          cd /opt/colcon_ws/src/gisnav/docker
          docker compose build gisnav
          docker tag $(docker images -q gisnav) ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
