name: Build and upload gisnav Docker image to GHCR

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows running manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  upload:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout GISNav
        uses: actions/checkout@v3
        with:
          path: colcon_ws/src/gisnav

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push gisnav images
        run: |
          cd colcon_ws/src/gisnav/docker
          docker buildx create --use
          docker compose -f docker-compose.yaml -f docker-compose.arm64.yaml build gisnav
          docker push
